name: Build and Deploy Next.js to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build do Next.js
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy automático no Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}       # token pessoal do Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}     # ID da organização no Vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID do projeto no Vercel
          working-directory: .                             # raiz do projeto
          alias-domains: casa-thereza-anjo-dos-animais.vercel.app
